title: git똥찬 개발자의 개발로그
author: hhaggang22
email: zhdlqkddnf@naver.com
copyright: © 2021 by hkkim
description: > # this means to ignore newlines until "show_excerpts:"
  This is Joanne's blog for writing about develop logs. 
  Trying to write all the issues I got and the things I knew.
  It might contain some mistake or error, so if you find it, make an issue or notice me. 
  Hope it will help you in any way. 
  Thanks-:)

show_excerpts: false # set to true to show excerpts on the homepage

lin:
  date_format: "%b %-d, %Y"

  # path to the author avatar image
  avatar_path: assets/images/myprofile.jpg

  # generate social links
  social_links:
    github: hhaggang22
    facebook: 김하경
    instagram: ha__gging
    linkedin: 김하경
    youtube_user: git똥찬 개발자
    youtube_channel: git똥찬 개발자

theme: lin

plugins:
  - jekyll-feed
  - jekyll-seo-tag
